import { EmbedBuilder, User, Message, AttachmentBuilder } from 'discord.js';
import { writeFileSync, unlinkSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { DiaryProcessingResult } from './types';

// Discord埋め込みメッセージのフォーマット機能
export class DiaryFormatter {
  // Larry による日記フィードバックの埋め込みとフォローアップメッセージを作成
  async createFeedbackResponse(
    result: DiaryProcessingResult,
    _originalContent: string,
    author: User,
    message: Message
  ): Promise<void> {
    const embed = new EmbedBuilder()
      .setTitle("📝 Larry's Diary Feedback")
      .setColor(0x00ae86)
      .setTimestamp()
      .setFooter({
        text: `Larry detected: ${this.getLanguageDisplayName(result.detectedLanguage)} • Canadian English Tutor`,
        iconURL: author.displayAvatarURL(),
      });

    // 元のターゲット文を追加
    embed.addFields({
      name: `Target Sentence (${this.getLanguageDisplayName(result.detectedLanguage)})`,
      value: this.truncateText(result.targetSentence, 1000),
      inline: false,
    });

    // 完全なメッセージ内容を生成
    const completeMessage = this.generateCompleteMessage(result, author);

    // メッセージファイルを作成
    const filePath = await this.createMessageFile(completeMessage, author.username);
    
    try {
      // ファイル添付を作成
      const attachment = new AttachmentBuilder(filePath, { name: 'message.txt' });
      
      // メイン埋め込みとファイルを一緒に送信
      await message.reply({ 
        embeds: [embed],
        files: [attachment]
      });
    } finally {
      // 一時ファイルを削除
      this.cleanupFile(filePath);
    }
  }

  // エラー時の埋め込みメッセージを作成
  createErrorEmbed(): EmbedBuilder {
    return new EmbedBuilder()
      .setTitle("❌ Larry's Translation Error")
      .setDescription(
        'Sorry, I encountered an error while processing your diary entry. Please try again later.'
      )
      .setColor(0xff0000)
      .setTimestamp();
  }

  // 言語名を表示用に変換
  private getLanguageDisplayName(language: string): string {
    switch (language) {
      case 'japanese':
        return '🇯🇵 Japanese';
      case 'english':
        return '🇺🇸 English';
      case 'mixing':
        return '🇯🇵🇺🇸 Mixed (JP + EN)';
      default:
        return '🌍 Other';
    }
  }

  // テキストを指定長で切り詰め
  private truncateText(text: string, maxLength: number): string {
    if (text.length <= maxLength) {
      return text;
    }
    return text.substring(0, maxLength - 3) + '...';
  }

  // 完全なメッセージ内容を生成（改行を適切に配置して読みやすく）
  private generateCompleteMessage(result: DiaryProcessingResult, author: User): string {
    const lines: string[] = [];
    
    // ヘッダー部分
    lines.push(`📝 Larry's Complete Diary Feedback for ${author.username}`);
    lines.push(`═══════════════════════════════════════════════════════`);
    lines.push(``);
    
    // 基本情報
    lines.push(`🎯 DETECTED LANGUAGE: ${this.getLanguageDisplayName(result.detectedLanguage)}`);
    lines.push(`📖 SCENARIO: ${result.scenario.toUpperCase().replace(/-/g, ' ')}`);
    lines.push(``);
    
    // ターゲット文
    lines.push(`📝 TARGET SENTENCE:`);
    lines.push(`${result.targetSentence}`);
    lines.push(``);
    lines.push(`═══════════════════════════════════════════════════════`);
    lines.push(``);

    // シナリオ別の内容を追加
    const scenarioLines = this.getScenarioContentLines(result);
    lines.push(...scenarioLines);

    // 質問回答を追加
    if (result.hasQuestions && result.questionAnswers && result.questionAnswers.length > 0) {
      lines.push(``);
      lines.push(`═══════════════════════════════════════════════════════`);
      lines.push(``);
      lines.push(`❓ QUESTIONS & ANSWERS:`);
      lines.push(``);
      
      result.questionAnswers.forEach((qa, index) => {
        lines.push(`Q${index + 1}: ${qa.question}`);
        lines.push(``);
        lines.push(`A${index + 1}: ${qa.answer}`);
        lines.push(``);
        if (index < result.questionAnswers!.length - 1) {
          lines.push(`---`);
          lines.push(``);
        }
      });
    }

    // フッター
    lines.push(`═══════════════════════════════════════════════════════`);
    lines.push(`Generated by Larry • Canadian English Tutor`);
    lines.push(`Timestamp: ${new Date().toISOString()}`);
    lines.push(``);

    // 改行で結合して返す
    return lines.join('\n');
  }

  // シナリオ別の内容を行配列で取得（改行を適切に配置）
  private getScenarioContentLines(result: DiaryProcessingResult): string[] {
    const lines: string[] = [];
    
    switch (result.scenario) {
      case 'japanese-only':
        if (result.threeLevelTranslations) {
          lines.push(`📚 THREE LEVEL ENGLISH TRANSLATIONS:`);
          lines.push(``);
          
          lines.push(`🟢 BEGINNER LEVEL:`);
          lines.push(`${result.threeLevelTranslations.beginner}`);
          lines.push(``);
          
          lines.push(`🟡 INTERMEDIATE LEVEL:`);
          lines.push(`${result.threeLevelTranslations.intermediate}`);
          lines.push(``);
          
          lines.push(`🔴 UPPER LEVEL:`);
          lines.push(`${result.threeLevelTranslations.upper}`);
          lines.push(``);
        }
        break;

      case 'japanese-with-try':
        if (result.threeLevelTranslations) {
          lines.push(`📚 THREE LEVEL ENGLISH TRANSLATIONS:`);
          lines.push(``);
          
          lines.push(`🟢 BEGINNER LEVEL:`);
          lines.push(`${result.threeLevelTranslations.beginner}`);
          lines.push(``);
          
          lines.push(`🟡 INTERMEDIATE LEVEL:`);
          lines.push(`${result.threeLevelTranslations.intermediate}`);
          lines.push(``);
          
          lines.push(`🔴 UPPER LEVEL:`);
          lines.push(`${result.threeLevelTranslations.upper}`);
          lines.push(``);
        }

        if (result.translationEvaluation) {
          lines.push(`═══════════════════════════════════════════════════════`);
          lines.push(``);
          
          lines.push(`🎯 TRANSLATION EVALUATION:`);
          lines.push(`${result.translationEvaluation.evaluation}`);
          lines.push(``);
          
          lines.push(`📝 STUDY POINTS:`);
          result.translationEvaluation.studyPoints.forEach((point, index) => {
            lines.push(`${index + 1}. ${point}`);
          });
          lines.push(``);
          
          lines.push(`💡 IMPROVEMENTS:`);
          lines.push(`${result.translationEvaluation.improvements}`);
          lines.push(``);
        }
        break;

      case 'english-only':
        if (result.japaneseTranslation && result.vocabularyExplanation && result.grammarExplanation) {
          lines.push(`🇯🇵 JAPANESE TRANSLATION:`);
          lines.push(`${result.japaneseTranslation}`);
          lines.push(``);
          
          lines.push(`📖 VOCABULARY EXPLANATION:`);
          lines.push(`${result.vocabularyExplanation}`);
          lines.push(``);
          
          lines.push(`📝 GRAMMAR EXPLANATION:`);
          lines.push(`${result.grammarExplanation}`);
          lines.push(``);
        }
        break;
    }
    
    return lines;
  }

  // メッセージファイルを作成
  private async createMessageFile(content: string, username: string): Promise<string> {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `larry-feedback-${username}-${timestamp}.txt`;
    const filePath = join(tmpdir(), filename);
    
    writeFileSync(filePath, content, 'utf8');
    return filePath;
  }

  // 一時ファイルを削除
  private cleanupFile(filePath: string): void {
    try {
      unlinkSync(filePath);
    } catch (error) {
      console.warn('Failed to cleanup temporary file:', filePath, error);
    }
  }
}
